# Generated by Django 2.1.1 on 2018-09-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qian', '0007_auto_20180911_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': '签到任务'},
        ),
        migrations.AlterModelOptions(
            name='log_a',
            options={'verbose_name_plural': '日志'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='lijie',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
